#
#
spring.application.name=motd
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

management.opentelemetry.resource-attributes.service.name=${spring.application.name}
management.opentelemetry.resource-attributes.service.namespace=sleepymouse
management.opentelemetry.resource-attributes.deployment.environment=${ENVIRONMENT:dev}

management.otlp.tracing.endpoint=http://alloy.observability.svc.cluster.local:4318/v1/traces
management.tracing.sampling.probability=1.0

management.otlp.metrics.export.url=http://alloy.observability.svc.cluster.local:4318/v1/metrics
management.metrics.tags.application=${spring.application.name}
